/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface User {
  uid: string;
  email: string;
  displayName: string;
  avatar: string;
  transitionType: string; // "bereavement" | "divorce" | "job-loss" | "relationship" | "transition" | "other"
  createdAt: string;
}

export type TransitionType = 
  | "bereavement" 
  | "divorce" 
  | "job-loss" 
  | "relationship-breakdown" 
  | "life-transition";

export interface MoodProfile {
  sadness: number;      // 0 to 100
  anxiety: number;      // 0 to 100
  anger: number;        // 0 to 100
  loneliness: number;   // 0 to 100
  guilt: number;        // 0 to 100
  hope: number;         // 0 to 100
  acceptance: number;   // 0 to 100
}

export interface JournalEntry {
  id: string;
  userId: string;
  text: string;
  title: string;
  audioUrl?: string;
  hasAudio?: boolean;
  moods: MoodProfile;
  overallMoodScore: number; // 1 to 10 scaled
  dominantEmotion: string;
  keywords: string[];
  aiResponse: string; // The Adaptive Micro-Support response generated by Gemini
  date: string; // YYYY-MM-DD
  createdAt: string;
}

export interface CommunityPost {
  id: string;
  category: TransitionType | "general";
  title: string;
  body: string;
  authorId: string;
  authorName: string;
  authorAvatar: string;
  anonymous: boolean;
  likes: number;
  likedBy: string[]; // List of userId
  replies: CommunityReply[];
  createdAt: string;
  tags?: string[];
}

export interface CommunityReply {
  id: string;
  postId: string;
  body: string;
  authorId: string;
  authorName: string;
  authorAvatar: string;
  anonymous: boolean;
  createdAt: string;
}

export interface SupportResource {
  id: string;
  name: string;
  type: "therapist" | "support-group" | "ngo" | "community-center";
  address: string;
  description: string;
  phone: string;
  website: string;
  latitude: number;
  longitude: number;
  distance?: number; // Calculated field
  cost: "free" | "sliding-scale" | "premium";
  specialization: string[];
  languages: string[];
  rating: number;
}

export interface WellnessCheckin {
  id: string;
  userId: string;
  moodScore: number; // 1 to 10
  subMoods: string[]; // e.g. "exhausted", "numb", "hopeful", etc.
  sleepHours: number;
  physicalActivity: boolean;
  createdAt: string;
}

export interface CopingSuggestion {
  title: string;
  description: string;
  category: "breathing" | "reflection" | "gratitude" | "wellness-reminder";
  durationMinutes: number;
}
